string archive_directory # If not empty it will dump rgb, depth, poses and intrinsics to this directory
string mesh_filepath # The filepath to save the mesh at

# Filtering parameters
# Minimum number of connected faces a surface needs
uint32 min_num_faces

# Filter by normal orientation
industrial_reconstruction_msgs/NormalFilterParams[] normal_filters
---
bool success
