bool use_default_settings # This will ignore everything below settings
string path_dataset # The path to dataset which includes a depth and color folder
string path_intrinsic # The path to camera_intrinsic.json which is usually in the dataset directory
bool has_tracking # false. This indicates if it should also find a pose information with the dataset
bool debug_mode # false

# Stages to run
bool make      # Step 1) make fragments from RGBD sequence
bool register_fragments  # Step 2) register all fragments to detect loop closure"
bool refine    # Step 3) refine rough registrations
bool integrate # Step 4) integrate the whole RGBD sequence to make final mesh

# Settings (Required if use_default_settings is set to false)
string name # Realsense bag file
float32 max_depth # 3.0
float32 voxel_size # 0.05,
float32 max_depth_diff # 0.07
float32 preference_loop_closure_odometry # 0.1
float32 preference_loop_closure_registration # 5.0
float32 tsdf_cubic_size # 3.0
string icp_method # "color"
string global_registration # "ransac"
bool python_multi_threading # true

---
bool success
string mesh_file
