string path_dataset # The path to dataset which includes a depth, color folder
string path_intrinsic # The path to camera_intrinsic.json which is usually in the dataset directory
bool global_optimization # True
bool debug_mode # false

open3d_interface_msgs/TSDFVolumeParams tsdf_params
open3d_interface_msgs/RGBDImageParams rgbd_params
open3d_interface_msgs/GlobalOptimizationParams global_opt_params
open3d_interface_msgs/ComputeRGBDOdometryParams compute_rgbd_odometry_params

---
bool success
string mesh_file
