#!/usr/bin/env python3
import rospy
from open3d_interface.realsense_recorder import main
import argparse
import sys

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
