#!/usr/bin/env python3
import rospy
from open3d_interface.tsdf_rgb_recorder import main
import sys

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
